# Generated by Django 6.0.5 on 2026-05-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming & Data'), ('ai_tools', 'AI Tools'), ('marketing', 'Marketing & Advertising'), ('analytics', 'Analytics & Platforms'), ('other_tools', 'Other Tools')], default='other', max_length=20),
        ),
    ]
