# Generated by Django 6.0.5 on 2026-05-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
